---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    app: petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
     containers:
       - name: petclinic
         image: pet
         imagePullPolicy: Never
         ports:
         - containerPort: 8088
           name: http
         volumeMounts:
         - name: app-config
           mountPath: /application.yml
           subPath: application.yml
           readOnly: true
     volumes:
     - name: app-config
       configMap:
         name: petclinic

---
apiVersion: v1
kind: Service
metadata:
  name: petclinic
spec:
  selector:
    app: petclinic
  ports:
  - name: http
    protocol: TCP
    port: 8088
    targetPort: 8088
  type: LoadBalancer

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic
data:
  application.yml: |
    server:
      port: 8088
